export const memberData = [
  {
    id: 1,
    image: 'https://res.cloudinary.com/realdevsquad/image/upload/w_200,h_200/profile/2LEt2spMNDUCpkjmbsfa/pmtjfsf2pmk1cdfxrtvr',
    name: 'vinayak',
    twitter: '/',
    linkedin: '/',
    instagram: '/',
    github: '/',
  },
  {
    id: 2,
    image: 'https://res.cloudinary.com/realdevsquad/image/upload/w_200,h_200/profile/C2XUDSTtDooWLJ44iBYr/m6m5ckgi6bjcbtk47fkl',
    name: 'vaibhav',
    twitter: '/',
    linkedin: '/',
    instagram: '/',
    github: '/',
  },
  {
    id: 3,
    image: 'https://res.cloudinary.com/realdevsquad/image/upload/w_200,h_200/profile/EYNHBSK7riBKY775OOMB/mfzbgspqgvj6unz34unm',
    name: 'pallab',
    twitter: '/',
    linkedin: '/',
    instagram: '/',
    github: '/',
  },
  {
    id: 4,
    image: 'https://res.cloudinary.com/realdevsquad/image/upload/w_200,h_200/profile/YzEVZ50DHr37oL1mqqbO/pkdvproffntqvh0thqh0',
    name: 'prakash',
    twitter: '/',
    linkedin: '/',
    instagram: '/',
    github: '/',
  },
  {
    id: 5,
    image: 'https://res.cloudinary.com/realdevsquad/image/upload/w_200,h_200/profile/1butZN1HmIr0rwQmaVXp/ulqgyqehd79tc6g8akl2',
    name: 'rohan',
    twitter: '/',
    linkedin: '/',
    instagram: '/',
    github: '/',
  },
  {
    id: 6,
    image: 'https://res.cloudinary.com/realdevsquad/image/upload/w_200,h_200/profile/XAF7rSUvk4p0d098qWYS/syvexswtmz6hx7nghrs4',
    name: 'ankush',
    twitter: '/',
    linkedin: '/',
    instagram: '/',
    github: '/',
  },
]