import Head from "next/head";
import Image from "next/image";
import { wrapper } from "@/src/store";
import serverApi from "../src/services/serverApi";
import NewMembersCard from "@/src/components/NewMember";
import { NEW_USER, NUM_MEMBERS_NUMBER } from "@/src/constants/AppConstants";
import styles from "@/styles/Home.module.css";
import MembersSection from "@/src/components/MembersSection/MembersSection";

const avatarImageSrc = require("../public/images/avatar.png");
const firstName = "Sunny";
const lastName = "Kumar";

type PictureType = {
  publicId: string;
  url: string;
};

type RolesType = {
  archived: boolean;
  member: boolean;
};

type MemberType = {
  id: string;
  yoe: number;
  picture: PictureType;
  github_id: string;
  linkedin_id: string;
  instagram_id: string;
  twitter_id: string;
  roles: RolesType;
  last_name: string;
  profileURL: string;
  designation: string;
  github_display_name: null;
  company: string;
  username: string;
  first_name: string;
  profileStatus: string;
  status: string;
  incompleteUserDetails: boolean;
};

type MembersResponseType = {
  message: string;
  members: MemberType[];
};

type PagePropsType = {
  membersResp: MembersResponseType;
};

type PropsType = {
  pageProps: PagePropsType;
};

export default function Home(props: PropsType) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div>
        <h1 className='text-center text-3xl font-bold'>Members section</h1>
        <MembersSection />
      </div>
      <div>
        <h1 className='text-center text-3xl font-bold'>{NEW_USER}</h1>
        <div className='flex flex-wrap w-full mx-auto justify-center'>
          {/* 
            Creates an array of length NUM_MEMBERS_NUMBER to map over. Will be changed after new API being available for new members
          */}
          {Array.from({ length: NUM_MEMBERS_NUMBER }).map((_, i) => (
            <NewMembersCard
              key={i}
              newMemberFirstName={firstName}
              newMemberLastName={lastName}
              newMemberImageSrc={avatarImageSrc}
            />
          ))}
        </div>
      </div>
    </div>
  );
}

export const getServerSideProps = wrapper.getServerSideProps(
  (store) => async () => {
    // TODO: Give types
    store.dispatch(serverApi.endpoints.getMembers.initiate());
    const data = await Promise.all(
      store.dispatch(serverApi.util.getRunningQueriesThunk())
    );
    const membersResp = data[0]?.data ?? {};
    return {
      props: { membersResp },
    };
  }
);
